<?php

namespace App\Lib;

class CleaningCreator extends EventCreator
{

    public function create($data, $event = null)
    {

        $data = $this->getEvent()->parseData($data);

        parent::create($data, $event); // TODO: Change the autogenerated stub
    }

    public function getEvent(): EventParser
    {
        return new CleaningParser();
    }

    public function getType()
    {
        return self::EVENT_TYPE;;
        // TODO: Implement setType() method.
    }
}