<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJQsHzk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJQsHzk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHJQsHzk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHJQsHzk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHJQsHzk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'HJQsHzk',
    'container.build_id' => '5a79cb8a',
    'container.build_time' => 1561199172,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJQsHzk');
