<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwUja9I\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwUja9I/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPwUja9I.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPwUja9I\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPwUja9I\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PwUja9I',
    'container.build_id' => 'd02328b3',
    'container.build_time' => 1561224677,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwUja9I');
