<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBQ0hx6A\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBQ0hx6A/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBQ0hx6A.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBQ0hx6A\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBQ0hx6A\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BQ0hx6A',
    'container.build_id' => 'a27caf47',
    'container.build_time' => 1559996844,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBQ0hx6A');
