<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q8Slo_c' shared service.

return $this->privates['.service_locator.Q8Slo_c'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('errorDecorator' => function (): \App\Service\ResponseErrorDecoratorService {
    return ($this->privates['App\Service\ResponseErrorDecoratorService'] ?? $this->privates['App\Service\ResponseErrorDecoratorService'] = new \App\Service\ResponseErrorDecoratorService());
}, 'team' => function (): \App\Entity\FootballTeam {
    return ($this->privates['.errored..service_locator.Q8Slo_c.App\Entity\FootballTeam'] ?? $this->load('getFootballTeamService.php'));
}, 'teamService' => function (): \App\Service\FootballTeamService {
    return ($this->privates['App\Service\FootballTeamService'] ?? $this->load('getFootballTeamServiceService.php'));
}));
