<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.10EawuH' shared service.

return $this->privates['.service_locator.10EawuH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('errorDecorator' => function (): \App\Service\ResponseErrorDecoratorService {
    return ($this->privates['App\Service\ResponseErrorDecoratorService'] ?? $this->privates['App\Service\ResponseErrorDecoratorService'] = new \App\Service\ResponseErrorDecoratorService());
}, 'userService' => function (): \App\Service\UserService {
    return ($this->privates['App\Service\UserService'] ?? $this->load('getUserServiceService.php'));
}));
