<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.x.rKWMX' shared service.

return $this->privates['.service_locator.x.rKWMX'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('errorDecorator' => function (): \App\Service\ResponseErrorDecoratorService {
    return ($this->privates['App\Service\ResponseErrorDecoratorService'] ?? $this->privates['App\Service\ResponseErrorDecoratorService'] = new \App\Service\ResponseErrorDecoratorService());
}, 'league' => function (): \App\Entity\FootballLeague {
    return ($this->privates['.errored..service_locator.x.rKWMX.App\Entity\FootballLeague'] ?? $this->load('getFootballLeague2Service.php'));
}, 'leagueService' => function (): \App\Service\FootballLeagueService {
    return ($this->privates['App\Service\FootballLeagueService'] ?? $this->load('getFootballLeagueServiceService.php'));
}));
