<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HWqWiuO' shared service.

return $this->privates['.service_locator.HWqWiuO'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authService' => function (): \App\Service\AuthService {
    return ($this->privates['App\Service\AuthService'] ?? $this->getAuthServiceService());
}, 'errorDecorator' => function (): \App\Service\ResponseErrorDecoratorService {
    return ($this->privates['App\Service\ResponseErrorDecoratorService'] ?? $this->privates['App\Service\ResponseErrorDecoratorService'] = new \App\Service\ResponseErrorDecoratorService());
}, 'userService' => function (): \App\Service\UserService {
    return ($this->privates['App\Service\UserService'] ?? $this->load('getUserServiceService.php'));
}));
