<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BchDU7b' shared service.

return $this->privates['.service_locator.BchDU7b'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('league' => function (): \App\Entity\FootballLeague {
    return ($this->privates['.errored..service_locator.BchDU7b.App\Entity\FootballLeague'] ?? $this->load('getFootballLeagueService.php'));
}));
