<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AuthController::issueJWTToken' => function () {
    return ($this->privates['.service_locator.HWqWiuO'] ?? $this->load('get_ServiceLocator_HWqWiuOService.php'));
}, 'App\\Controller\\FootballLeagueController::createLeague' => function () {
    return ($this->privates['.service_locator.UPvaeps'] ?? $this->load('get_ServiceLocator_UPvaepsService.php'));
}, 'App\\Controller\\FootballLeagueController::deleteLeague' => function () {
    return ($this->privates['.service_locator.x.rKWMX'] ?? $this->load('get_ServiceLocator_X_RKWMXService.php'));
}, 'App\\Controller\\FootballLeagueController::getLeagueTeams' => function () {
    return ($this->privates['.service_locator.BchDU7b'] ?? $this->load('get_ServiceLocator_BchDU7bService.php'));
}, 'App\\Controller\\FootballTeamController::createTeam' => function () {
    return ($this->privates['.service_locator.I4mNHqH'] ?? $this->load('get_ServiceLocator_I4mNHqHService.php'));
}, 'App\\Controller\\FootballTeamController::deleteTeam' => function () {
    return ($this->privates['.service_locator.Q8Slo_c'] ?? $this->load('get_ServiceLocator_Q8SloCService.php'));
}, 'App\\Controller\\FootballTeamController::updateTeam' => function () {
    return ($this->privates['.service_locator.Q8Slo_c'] ?? $this->load('get_ServiceLocator_Q8SloCService.php'));
}, 'App\\Controller\\UserController::createUser' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController::deleteUser' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController::getUserByMail' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController::getUserList' => function () {
    return ($this->privates['.service_locator.1hjP8Jh'] ?? $this->load('get_ServiceLocator_1hjP8JhService.php'));
}, 'App\\Controller\\UserController::updateUser' => function () {
    return ($this->privates['.service_locator.p9rr06T'] ?? $this->load('get_ServiceLocator_P9rr06TService.php'));
}, 'App\\Controller\\AuthController:issueJWTToken' => function () {
    return ($this->privates['.service_locator.HWqWiuO'] ?? $this->load('get_ServiceLocator_HWqWiuOService.php'));
}, 'App\\Controller\\FootballLeagueController:createLeague' => function () {
    return ($this->privates['.service_locator.UPvaeps'] ?? $this->load('get_ServiceLocator_UPvaepsService.php'));
}, 'App\\Controller\\FootballLeagueController:deleteLeague' => function () {
    return ($this->privates['.service_locator.x.rKWMX'] ?? $this->load('get_ServiceLocator_X_RKWMXService.php'));
}, 'App\\Controller\\FootballLeagueController:getLeagueTeams' => function () {
    return ($this->privates['.service_locator.BchDU7b'] ?? $this->load('get_ServiceLocator_BchDU7bService.php'));
}, 'App\\Controller\\FootballTeamController:createTeam' => function () {
    return ($this->privates['.service_locator.I4mNHqH'] ?? $this->load('get_ServiceLocator_I4mNHqHService.php'));
}, 'App\\Controller\\FootballTeamController:deleteTeam' => function () {
    return ($this->privates['.service_locator.Q8Slo_c'] ?? $this->load('get_ServiceLocator_Q8SloCService.php'));
}, 'App\\Controller\\FootballTeamController:updateTeam' => function () {
    return ($this->privates['.service_locator.Q8Slo_c'] ?? $this->load('get_ServiceLocator_Q8SloCService.php'));
}, 'App\\Controller\\UserController:createUser' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController:deleteUser' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController:getUserByMail' => function () {
    return ($this->privates['.service_locator.10EawuH'] ?? $this->load('get_ServiceLocator_10EawuHService.php'));
}, 'App\\Controller\\UserController:getUserList' => function () {
    return ($this->privates['.service_locator.1hjP8Jh'] ?? $this->load('get_ServiceLocator_1hjP8JhService.php'));
}, 'App\\Controller\\UserController:updateUser' => function () {
    return ($this->privates['.service_locator.p9rr06T'] ?? $this->load('get_ServiceLocator_P9rr06TService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
