<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\ExceptionSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/ExceptionSubscriber.php';
include_once $this->targetDirs[3].'/src/Service/ResponseErrorDecoratorService.php';

return $this->privates['App\EventSubscriber\ExceptionSubscriber'] = new \App\EventSubscriber\ExceptionSubscriber(($this->privates['App\Service\ResponseErrorDecoratorService'] ?? $this->privates['App\Service\ResponseErrorDecoratorService'] = new \App\Service\ResponseErrorDecoratorService()));
