<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Q8Slo_c.App\Entity\FootballTeam' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.Q8Slo_c": it references class "App\\Entity\\FootballTeam" but no such service exists.');
