<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.x.rKWMX.App\Entity\FootballLeague' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.x.rKWMX": it references class "App\\Entity\\FootballLeague" but no such service exists.');
